# Anexos {.unnumbered}

## CAPÍTULO VII 
### NOB SUAS 2012
Art. 1º A política de assistência social, que tem por funções a proteção social, a vigilância socioassistencial e a defesa de direitos, organiza-se sob a forma de sistema público não contributivo, descentralizado e participativo, denominado Sistema Único de Assistência Social - SUAS. 

Art. 2º São objetivos do SUAS: (...)

XI - afiançar a vigilância socioassistencial e a garantia de direitos como funções da política de assistência social.

Art. 12. Constituem responsabilidades comuns à União, Estados, Distrito Federal e Municípios: (...)

XIII - apoiar técnica e financeiramente os Estados, e o Distrito Federal e Municípios na implantação da vigilância socioassistencial;

Art. 15. São responsabilidades dos Estados: (...)

IX - apoiar técnica e financeiramente os Municípios na implantação da vigilância socioassistencial;

Art. 78. O cofinanciamento dos serviços socioassistenciais, observada a disponibilidade orçamentária e financeira de cada ente federativo, efetivar-se-á a partir da adoção dos seguintes objetivos e pressupostos: (...)II - implantação e oferta qualificada de serviços em territórios de vulnerabilidade e risco social, de acordo com o diagnóstico das necessidades e especificidades locais e regionais, considerando os parâmetros do teto máximo estabelecido para cofinanciamento da rede de serviços e do patamar existente; (...)§2º Para implantação de que trata o inciso II serão considerados os dados do diagnóstico socioterritorial e da Vigilância Socioassistencial, por meio do cruzamento de indicadores, com o objetivo de estabelecer prioridades progressivas até o alcance do teto a ser destinado a cada ente federativo, por nível de proteção.