# Macroatividades da Vigilância Socioassistencial
Embora, do ponto de vista organizacional, a NOB 2012 determine a instauração da Vigilância Socioassistencial como uma área que compõe a gestão do SUAS, é necessário compreender sua estreita relação com as áreas de Proteção Social Básica e de Proteção Social Especial, e sua Unidades diretamente responsáveis pela oferta dos serviços socioassistenciais à população.

As unidades de proteção básica ou especial nas quais são ofertados os serviços e benefícios socioassistenciais são provedoras de informações para a Vigilância Socioassistencial sempre que registram e armazenam de forma adequada dados relativos ao território e ao perfil dos usuários, além de informações referentes ao tipo e volume de atendimentos que realizam, contribuindo assim para o mapeamento de situações de risco e vulnerabilidade e de eventos de violações de direitos em determinado território. Assim, o ponto de partida para a Vigilância Socioassistencial é, em larga medida, o próprio conhecimento produzido e acumulado das equipes técnicas da Assistência Social.

Por outro lado, os serviços devem ser consumidores das informações processadas ou produzidas pela área de Vigilância Socioassistencial, e esta deve, para cumprir seus objetivos, fornecer aos serviços informações estruturadas que contribuam para que estes avaliem sua própria atuação, ampliem seu conhecimento sobre as características da população e do território de forma a melhor atender às necessidades e demandas existentes, e ainda, planejem e executem ações de busca ativa que assegurem a oferta de serviços e benefícios às famílias e indivíduos mais vulneráveis, superando a atuação pautada exclusivamente pela demanda espontânea.

A informação registrada tem que ter sentido e utilidade para quem registra. Nesse sentido, é pertinente afirmar que a efetiva materialização da Vigilância Socioassistencial, no sentido que lhe atribui a PNAS, ocorre quando a gestão, o planejamento e execução dos serviços são orientados por uma perspectiva de produção e utilização de informações objetivas acerca da realidade social, que permite qualificar tecnicamente a tomada de decisões, sem, contudo, negar a importância do conteúdo político e social das escolhas e ações realizadas pelos gestores e profissionais.

Neste sentido, a Vigilância Socioassitencial contribui para a qualificação dos serviços socioassistenciais por meio de um conjunto de atividades que serão discutidas nos tópicos apresentados a seguir.

## Organização, estruturação e padronização de informações
Não são desprezíveis a quantidade de informações que nossa sociedade produz. Há um grande volume de informações que podem ser úteis para a gestão estratégica do SUAS. No entanto, grande parte dessa informação se encontra fragmentada, desestruturada e desorganizada. Geralmente há um número excessivo de instrumentos de registro da informação, com dados repetidos, registros da Assistência Social com preponderância de perguntas sobre outras áreas de conhecimento, entre muitas outras situações.

Assim, um primeiro passo na implantação da Vigilância Socioassistencial é identificar as fontes de dados e informações já existentes nos territórios em que atua. As fontes de informação podem ser as mais diversas possíveis, indo desde uma série de aplicativos disponibilizados nacionalmente, como Cadúnico, CECAD, Censo SUAS, como informações como informações coletadas pelos profissionais dos serviços em sua convivência com o território. Após a identificação das fontes de dados disponíveis é necessário que a equipe de trabalhadores do SUAS faça uma leitura minuciosa das informações e, assim, consiga definir um rol de informações que deve ser analisadas sistematicamente.

Sob este prisma indicado, por exemplo, é que os profissionais da Vigilância Socioassistencial invistam um tempo em explorar os aplicativos como o Censo SUAS, o Registro Mensal de Atendimentos (RMA), o Sistema de Identificação de Domicílios em Vulnerabilidade (IDV) e aplicativos estaduais e municipais.

Portanto, é função da Vigilância sistematizar as informações em seu âmbito de atuação para facilitar o processo de planejamento e execução de serviços e, nos casos que se fizerem necessários, propor novas formas e questões para a coleta de informações. Por exemplo, propor metodologias de construção coletiva do conhecimento nos CRAS e CREAS, auxiliar aos técnicos a conhecerem seus territórios de abrangência, propor formulários de coleta de dados, fomentar sistemas informatizados, ente outros. Para isto, é necessário que a Vigilância Socioassistencial se preocupe com a padronização e fluxos nos registros da informação.

Nem todas as informações necessárias para o planejamento da Assistência Social são de gestão da própria assistência, por exemplo, informações de saúde, habitação, educação podem ser relevantes para se cumprir as responsabilidades da Vigilância, portanto, nestes casos, é imprescindível também a articulação com outros setores e gerências a fim de cruzar os dados que se fizerem necessários.

Em casos mais específicos, será necessário o diálogo sobre determinados conceitos e variáveis para que se possa utilizar a informação de forma articulada intersetorialmente, e discutir questões como a interoperabilidades de sistemas informatizados. Em municípios em regiões metropolitanas, por exemplo, poderá ser necessária a interlocução entre as Vigilâncias nos diversos municípios para a indução de um planejamento em conjunto.

Em locais onde a cultura do registro ainda não está estabelecida, a Vigilância Sociassistencial terá que enfrentar, ainda, o desafio do fomento desta cultura e o zelo pela informação, através da capacitação e do apoio técnico.

É importante lembrar que o registro e organização das informações é um direito dos usuários dos serviços da Assistência Social, por isso, a Vigilância Socioassistencial deve cuidar do adequado armazenamento da informação, principalmente no que se refere ao sigilo das informações.

## Gerenciamento e consulta de sistemas informatizados
Como dito na seção anterior, os técnicos da Vigilância Socioassitencial devem explorar os aplicativos e sistemas que lhes permitem acessar informações que auxiliem a política. Cada aplicativo tem uma forma de manuseio diferenciada. Quando técnicos de setores distintos usam o mesmo sistema, há um custo de tempo e esforço para que cada um deles aprenda o manuseio, o que aumenta a probabilidade de erro. Assim, centralizar tais atividades na Vigilância se traduz em uma forma mais eficaz de lidar com as informações. 

No entanto, a atividade da Vigilância vai além da leitura dos dados. A Vigilância é corresponsável pelas informações prestadas e pelo próprio sistema. Então, por exemplo, a Vigilância deve coordenar o processo de preenchimento do CADSUAS, do Censo SUAS e do RMA, analisando e validando as informações prestadas por outras áreas. Quando seu município/estado propõe um sistema, a Vigilância deve ter papel central em sua elaboração e qualificação, bem como posterior gestão e monitoramento. Quando não está em seu âmbito de atuação, deve ser ativo em informar problemas identificados. Logo, espera-se da Vigilância um olhar qualificado sobre os números e dados, que lhe permite efetivar a gestão da informação.

## Elaboração de diagnósticos e estudos
Uma das principais funções da Vigilância Socioassistencial é a produção de diagnósticos socioassistenciais. O diagnóstico é uma análise interpretativa que possibilita a leitura de uma determinada realidade social. A partir desta leitura, o município conhece melhor as necessidades e demandas dos cidadãos. O diagnóstico socioterritorial possibilita aos responsáveis e operadores da política de assistência social a apreenderem as particularidades do território sob o qual estão inseridos e detectarem as características e dimensões das situações de precarização que vulnerabilizam e trazem riscos e danos aos cidadãos, à sua autonomia, socialização e ao convívio familiar. O diagnóstico deve levantar além das carências, também as potencialidades do lugar, o que possibilita ações estratégicas para fomentar estas potencialidades.

Por outro lado, o diagnóstico deve levantar a rede de proteção social no território, seja ela a rede referenciada da Assistência Social ou a rede das demais políticas públicas, verificando quantas famílias já estão sendo atendidas e, logicamente, a quantidade de famílias que demandam os serviços, mas ainda 
não estão sendo adequadamente atendidas.

Assim, a partir da identificação das particularidades do território e do conhecimento das famílias, os profissionais que atuam na política de assistência social podem formular estratégias com vistas à proteção social e a melhoria da qualidade de vida da população.

Os municípios possuem estruturas, realidades, dimensões territoriais e populacionais bem distintos, por isso, os diagnósticos devem ser personalizados, dialogando com as particularidades locais a fim de que a comunidade demande serviços segundo suas próprias características.

É papel da Vigilância contribuir com as áreas de proteção social básica e de proteção social especial na elaboração de planos e diagnósticos, tais como diagnósticos dos territórios de abrangência dos CRAS e diagnósticos e planos para enfrentamento do trabalho infantil, dentre outros. Assim, o diagnóstico se concretiza através de um ou mais relatórios técnicos, que trazem subsídios para a tomada de decisão política.

Sob este aspecto, é importante ressaltar a relação do diagnóstico socioterritorial e os planos de Assistência Social. O plano deve conter a caracterização da realidade social dos municípios, portanto, deve conter um diagnóstico. No entanto, o diagnóstico socioterritorial não se limita a realização do plano.

As informações sistematizadas nestes relatórios podem ser de cunho secundário ou primário, isto é, informações já existentes em base de dados ou registros administrativos ou informações que o próprio setor produza. No que se refere ao levantamento de dados primários, é importante ressaltar o conhecimento das equipes técnicas sobre o território, suas características e dificuldades. Por exemplo, apenas estando nas unidades, circulando em seu território e conversando com lideranças comunitárias, é possível verificar os limites de territórios de gangues e facções, quais os trechos do território mais distantes, dificuldades de travessia para as famílias, entre outras características próprias do território de abrangência das unidades.

Além disso, processos de construção coletiva, com a participação das equipes técnicas das unidades e de usuários, podem ajudar na elaboração do diagnóstico e sua melhor interlocução com as necessidades da política.

Em suma, é reponsabilidade da Vigilância Socioassistencial elaborar e atualizar periodicamente o diagnóstico socioterritorial (do município, do estado ou do país) que deve conter informações especializadas dos riscos e vulnerabilidades e da consequente demanda de serviços de proteção social básica e de proteção social especial, bem como informações igualmente especializadas referentes ao tipo e volume de serviços efetivamente disponíveis e ofertados à população. O Diagnóstico deverá ser um instrumento dinâmico, participado e que permite uma compreensão da realidade social. Deverá incluir a identificação das necessidades e a detecção dos problemas prioritários e respectivas causalidades, em como dos recursos e potencialidades locais, que constituem reais oportunidades de desenvolvimento.

É importante que os municípios incorporem a utilização da base de dados do Cadastro Único de Programas Sociais – CadÚnico – como ferramenta para construção de mapas de vulnerabilidade social dos territórios, para traçar o perfil de populações vulneráveis e para estimar a demanda potencial dos serviços de Proteção Social Básica.

Em muitas situações, é comum encontrar diagnósticos que focam apenas em questões socioeconômicas mais amplas, como educação e saúde, questões que são importantes, mas não dialogam diretamente com o planejamento específico da Assistência Social, por isso, é importante ressaltar que os diagnósticos socioterritoriais no âmbito da Assistência devem se preocupar em levantar informações úteis para a própria Assistência, como situações de trabalho infantil, idosos dependentes, situações de violação de direitos, entre outros.

::: {.callout-warning}
## Sugestão

**Sugestão para apresentação de dados na elaboração do Diagnóstico Socioterritorial do Município ou Estado**

1) Variáveis e indicadores de contexto. Visam apresentar as condições gerais de desenvolvimento econômico e social dos municípios, microregiões e estados. De forma geral, devem abordar de forma muito sintética as informações essenciais das seguintes áreas: demografia, educação, saúde, trabalho, infraestrutura urbana, economia e meio ambiente. Devem ocupar não mais que 25% do documento produzido.

2) Variáveis e indicadores de caracterização da demanda potencial para os Serviços e Benefícios da Assistência Social. Objetivam apresentar uma referência numérica que possa ser utilizada como proxi da demanda potencial, ou como dimensionamento do público alvo, para cada um dos serviços e benefícios do SUAS em um dado território. Devem considerar, todos os Serviços Socioassistenciais Tipificados, os Benefícios Eventuais, o Benefício de Prestação Continuada – BPC e o benefício pago por meio do Programa Bolsa Família.

3) Variáveis e indicadores relativos à estrutura de oferta dos Serviços e Benefícios da Assistência Social. Objetivam apresentar, por meio de dados quantitativos, informações sobre a existência, ou não, de oferta de cada um dos serviços tipificados e benefícios do SUAS em um dado território, bem como a caracterização do volume de oferta e/ou da capacidade instalada, devendo ainda, quando possível, incluir indicadores relativos à qualidade da oferta instalada e à existência e volume de financiamento federal para os referidos serviços e benefícios.

4) Variáveis e indicadores relativos à estrutura de oferta das demais políticas públicas, exclusivamente no que se refere aos pontos de contato e de complementariedade entre estas e a Assistência Social. Objetivam apresentar, por meio de dados numéricos e de dados categóricos, informações sobre a existência, ou não, de outras ofertas que, embora não integrem as ações de assistência social, constituem “retaguardas” ou pontos de apoio indispensáveis à dimensão intersetorial da atenção aos usuários da política de assistência. Nesse sentido, se destacam estruturas de ofertas, relacionadas à Justiça, aos serviços de saúde mental, Equipes/Unidades de Saúde da Família, Programas de Educação em horário integral etc).

5) Indicadores que correlacionem demanda e oferta, segundo os Serviços Socioassistenciais Tipificados e, eventualmente, públicos específicos. Objetiva apresentar indicadores que permitam analisar, direta ou indiretamente, a cobertura dos serviços e benefícios em um determinado território. A análise da cobertura ocorrerá de forma direta quando for possível estimar com razoável precisão o volume da demanda efetiva e da oferta existente, podendo então a relação ser expressa em um percentual de cobertura. A análise da cobertura ocorrerá de forma indireta nas situações em que se tem apenas o dimensionamento genérico do público alvo de um serviço, mas não é possível obter dados mais precisos sobre o volume efetivo da demanda e, por conseqüência, do nível ótimo da oferta. Neste caso, pode-se trabalhar com taxas ou razões que permitam analisar um território comparativamente a outros territórios ou à média do estado, ainda que não seja possível aferir o percentual de cobertura do serviço. Como exemplo desse tipo de indicador podemos citar uma taxa que descreva o número de vagas existentes em abrigos para crianças e adolescentes em um determinado território para cada grupo de 100 mil crianças e adolescentes. Tal indicador permitiria aferir que em uma microrregião existem 60 vagas para cada 100 mil crianças, ao passo que em outra região existem apenas 15 vagas para cada 100 mil crianças. No caso em questão, adota-se uma proxi genérica da demanda, ou seja, assume-se que todas as crianças de 0 a 17 anos constituem potencialmente o público alvo dos serviços de acolhimento, uma vez que não é possível estimar com precisão razoável a demanda efetiva, que seria dada pelo número de crianças e adolescentes que necessitam ser acolhidas em função de situações de abandono ou violência.
:::

### Mapa da Rede Socioassistencial e Intersetorial
A Vigilância Sociassistencial deve elaborar relatório com georeferenciamento das unidades:

1) públicas e privadas da rede referenciada, isto é, a rede de proteção social de Assistência Social e 

2) públicas e privadas de outras políticas públicas que possam auxiliar no desenvolvimento da capacidade protetiva das famílias, como escolas, saúde da família, núcleos de inclusão produtiva, conselhos tutelares, entre muitas outras. 

O Sistema Único de Assistência Social (SUAS) reconhece os Centros de Referência em Assistência Social (CRAS) e os Centros de Referência Especializados em Assistência Social (CREAS) como equipamentos capazes de organizar e listar um cardápio de serviços e apresentá-lo ao cidadão, possibilitando a este caminhar livremente dentro da série de equipamentos, serviços, benefícios e políticas existentes em seu território.

O SUAS reconhece que não é de sua responsabilidade enfrentar todas as situações de vulnerabilidades de uma família, mas coloca sobre os profissionais de suas unidades o encargo de encaminhar seus usuários para a rede de políticas públicas a fim de minimizá-la. Para empreender tais tarefas, o CRAS e CREAS devem conhecer e se articular com atores que formam a rede de serviços de Proteção Social, entendida aqui como a rede setorial da Assistência Social e intersetorial de outras políticas sociais, em seu território. Dessa forma, a Vigilância Socioassistencial deve apoiar as unidades na efetivação da articulação com a rede socioassistencial.

Tal georeferenciamento não precisa ser executado necessariamente com softwares específicos. O importante é clareza da localização de unidades que podem, direta ou indiretamente, efetivar os direitos sociais dos usuários.

Além disso, é de responsabilidade da Vigilância a gestão e alimentação de outros sistemas de informação que provêm dados sobre a rede socioassistencial e sobre os atendimentos por ela realizados, quando estes não forem específicos de um programa, serviço ou benefício. Um exemplo, é a gestão do cadastro de unidades da rede socioassistencial no CadSUAS.

## Monitoramento e Avaliação
No âmbito do SUAS o monitoramento é uma atividade da Vigilância Socioassistêncial, por meio da qual procura-se levantar continuamente informações sobre os serviços ofertados à população, particularmente no que diz respeito a aspectos de sua qualidade e de sua adequação quanto ao tipo e volume da oferta. O monitoramento é fundamental para a identificação de problemas, assim como para subsidiar as estratégias de “correção dos rumos”.

A NOB/SUAS 2012 traz as atividades de gestão da informação, monitoramento e avaliação para dentro do capítulo da Vigilância Socioassistencial, dando maior clareza sobre a relação entre estas atividades. Mesmo que sejam outros órgãos que realizam pesquisas, estudos e relatórios, é de responsabilidade da Vigilância Socioassistencial a devida tradução e sistematização destas informações.

Ao mesmo tempo, é de responsabilidade da Vigilância Socioassistencial, em conjunto com as proteções sociais, organizar atividades de monitoramento in loco, visitas e encontros.

Assim, da mesma forma que os diagnósticos socioterritoriais, o monitoramento organiza informações de dados secundários, com dados provenientes de sistemas de informação, base de dados oficiais, relatórios administrativos, bem como dados primários, através de visitas in loco.

O Censo SUAS consolidou-se como uma referência nacional que materializa uma experiência exitosa de monitoramento do SUAS. Seus dados têm sido utilizados intensamente pelos gestores para o planejamento e aprimoramento do sistema.

A Vigilância também cabe orientar quanto aos procedimentos de registro das informações referentes aos atendimentos realizados pelas unidades da rede socioassistencial, zelando pela padronização e qualidade dos mesmos, uma vez que tais informações são de fundamental relevância para a caracterização da oferta de serviços e para a notificação dos eventos de violação de direitos.

Assim, a Vigilância deve acompanhar a alimentação dos sistemas de informação que provêm dados sobre a rede socioassistencial e sobre os atendimentos por ela realizados, mantendo permanente diálogo com as áreas de Proteção Social Básica e de Proteção Social Especial, que são diretamente responsáveis pela alimentação dos sistemas do seu âmbito de atuação.

A Vigilância socioassistencial deve estabelecer, com base nas normativas existentes e no diálogo com as demais áreas técnicas, padrões de referência para avaliação da qualidade dos serviços ofertados pela rede socioassistencial e monitorá-los por meio de indicadores.

Também, deve coordenar em nível municipal, de forma articulada com as áreas de Proteção Social Básica e de Proteção Social Especial, as atividades de inspeção da rede socioassistencial pública e privada, de forma a avaliar periodicamente a observância dos padrões de referência relativos à qualidade dos serviços ofertados.

Como veremos mais tarde, os principais instrumentos de análise das unidades da Rede Socioassistencial nacionalmente, são o Censo SUAS e o CADSUAS. É de responsabilidade da Vigilância coordenar o processo de realização anual do Censo SUAS, zelando pela qualidade das informações coletadas e gerir as informações prestadas no CADSUAS, a fim de que não hajam erros de registros, como unidades duplicadas.

É importante relembrar que no âmbito do SUAS, o monitoramento não tem caráter punitivo, mas sim instrutivo. Não cabe a Assistência realizar atividades de caráter fiscalizatório. Situações de violação devem ser compulsoriamente encaminhadas aos órgãos competentes.

### Avaliação
Assim como o monitoramento, a NOB/SUAS 2012 traz para dentro do escopo da Vigilância Socioassistencial a responsabilidade de efetivar a atividade de avaliação. Isto não significa dizer que toda pesquisa ou estudo será produzido exclusivamente pela Vigilância, mas que é esta a área responsável por apoiar a gestão na escolha de pesquisas que se adequem às necessidades do SUAS.

Portanto, a Vigilância deve propor ou auxiliar na proposição de temáticas, acompanhar o processo e traduzir os resultados para o âmbito do SUAS.

As avaliações devem ser realizadas por organizações capacitadas para tal. O processo deve responder adequadamente aos requisitos exigidos para a contratação destas organizações pela administração pública.

Como apontado pela NOB/SUAS 2012, as avaliações no âmbito do SUAS devem abordar a gestão, os serviços, os programas, os projetos e os benefícios socioassistenciais, isto é, é objeto de avaliação no âmbito do SUAS todas as situações que interferem no desenho da política.

## Planejamento e organização de ações de busca ativa
Segundo o Caderno Técnico do Brasil Sem Miséria, a Busca Ativa refere-se à localização, inclusão no Cadastro Único e atualização cadastral de todas as famílias pobres, assim como o encaminhamento destas famílias aos serviços da rede de proteção social. 

::: {.callout-tip appearance="minimal"}

A Busca Ativa se desdobra em três estratégias: 

(1) Busca Ativa para inclusão no Cadasto Único: trata-se de localizar as famílias extremamente pobres, 
incluí-las no CadÚnico e manter suas informações sempre atualizadas;

(2) Busca Ativa para Acessar Benefícios: incluir no Bolsa Família, no Bolsa Verde, no Fomento a Atividades Produtivas, no Programa de Erradicação do Trabalho Infantil e no Benefício de Prestação Continuada todas as famílias que atendam os critérios de elegibilidade;

(3) Busca Ativa para Acessar Serviços: nesse caso, o Estado assegura que as famílias extremamente pobres tenham acessos aos serviços sociais básicos de saúde, saneamento, educação, assistência social, trabalho e segurança alimentar e nutricional, entre outros. (Brasil, 2011 – Brasil sem miséria, caderno técnico).
:::

Cabe à Vigilância fornecer sistematicamente às unidades da rede socioassistencial, especialmente aos CRAS e CREAS, informações e indicadores territorializados – produzidos a partir de dados do CadÚnico e de outras fontes – objetivando auxiliar as ações de busca ativa e subsidiar as atividades de planejamento e avaliação dos próprios serviços. Tal modelo implica, não apenas, o planejamento da oferta com base no diagnóstico da demanda, mas também, a instituição da busca ativa como método estratégico de efetivação do acesso, potencializando o caráter preventivo das ações, ou, no mínimo, evitando o agravamento dos danos. A Vigilância Socioassistencial deve subsidiar as proteções com informações a fim de que estas sejam capazes de ir onde os mais vulneráveis estão.

Assim, a Vigilância Socioassistencial possui, necessariamente, o compromisso com a instituição e consolidação de um modelo de atenção que, partindo do reconhecimento e identificação das necessidades da população, aja proativamente para assegurar a oferta e efetivar o acesso das famílias e indivíduos aos serviços socioassistenciais.

Para isso, devem incorporar a utilização da base de dados do Cadastro Único de Programas Sociais – CadÚnico – como instrumento permanente para identificação, e consequente orientação para busca ativa, das famílias que apresentam características de potenciais demandantes dos distintos serviços ofertados pela rede socioassistencial.

Além do plano Brasil sem Miséria, o governo desenhou e está implementando uma série de ações (Brasil carinhoso, Plano Integrado de Enfrentamento ao Crack e outras Drogas, PRONATEC, entre outras) que visam a inclusão das famílias em serviços de Proteção Social.

Dentro da visão do Plano, a Assistência Social, devido a sua capilaridade no território, tem a responsabilidade de realizar a busca ativa. Assim, a partir do plano, o SUAS tem suas responsabilidades gradativamente aumentadas e as ações de Transferência de Renda e do SUAS se tornam cada vez mais integradas. Por um lado, o SUAS fica responsável pelo processo de busca ativa das famílias extremamente pobres, incluindo-as no Bolsa Família e por outro, com o crescimento do número de famílias mais vulneráveis no Bolsa Família, aumenta o número de famílias, inclusive as famílias em descumprimento, que devem ser prioritariamente atendidas no acompanhamento familiar do SUAS.

## Notificações de Violências e Violações de Direitos
A Vigilância Socioassistencial deve organizar, normatizar e gerir, no âmbito da Política de Assistência Social, o sistema de notificações para eventos de violação de direitos, estabelecendo instrumentos e fluxos necessários à sua implementação e funcionamento. Tal sistema deve contemplar, no mínimo, o registro e notificação de violações de direitos que envolvam eventos de violência física intrafamiliar, de abuso ou exploração sexual de crianças e adolescentes e de trabalho infantil.

A Vigilância Socioassistencial deverá montar uma sistemática que permita conhecer os eventos de violação de direitos que ocorrerem nos territórios. As Escolas, as Polícias, as Igrejas são parceiras imprescindíveis para identificação destes eventos. Essas informações deverão nortear as ofertas de serviços socioassistenciais no município, em especial, os Serviços de Média e Alta Complexidade.