# Considerações Finais
Para finalizar, propõe-se aqui analisar os avanços da área de Vigilância Socioassistencial nestes 9 anos de implantação do SUAS. Para tanto, é indispensável recuperar as deliberações das Conferências Nacionais de Assistência Social, em particular as Metas e Estratégias que integram o Plano Decenal de Assistência Social, que devem ser realizadas até o ano de 2015.

Dentre as metas e estratégias do Plano Decenal merece destaque, por sintetizar várias outras metas e estratégias, aquela que lança aos gestores o SUAS, na forma de deliberação, o seguinte desafio: “Implantar e implementar a Vigilância Socioassistencial em todos os municípios”. 

Outras metas e estratégias mais específicas, relacionadas à Vigilância, apontam para desafios, tais como: desenvolvimento e integração de sistemas de informações; desenvolvimento de capacidades para realização de diagnósticos das ofertas realizadas pela rede socioassistencial; padronização de registros de informações no âmbito do SUAS; implantação das notificações de violências e violações de direitos, implantação nacional de Prontuários no âmbito do SUAS; produção de diagnósticos de riscos e vulnerabilidades, utilização do CadÚnico como instrumento para a Vigilância; dentre outras.

O governo federal, no ano de 2010, instituiu formalmente na SNAS/MDS uma área específica responsável pela Vigilância Socioassistencial. Dados do Censo SUAS 2012 apontam que a Vigilância Socioassistencial está instituída formalmente em apenas 6 estados, embora outros 12 estados declarem possuir alguma área que se responsabiliza “de maneira informal” pela Vigilância. No que se refere aos municípios, 30% afirmam ter instituído formalmente esta área, enquanto 34% declaram que a área está constituída “de maneira informal” e em outros 36% não existe nenhuma iniciativa de organização da área de Vigilância na estrutura da Secretaria de Assistência Social.

É importante destacar que, desde a instituição do SUAS em 2005, muitas ações foram sendo desenvolvidas para viabilizar a implantação da Vigilância Socioassistencial. De certa maneira, pode-se dizer que no período entre 2005 e 2011 foi sendo aprimorada a concepção da Vigilância e desenvolvidos os instrumentos e meios técnicos que viabilizam a sua efetiva implantação no atual momento do SUAS.

Iniciativa de grande relevância foi a criação do Censo SUAS no ano de 2007, e sua realização anual desde então. Regulamentado pelo Decreto 7.334/2010, o Censo SUAS possibilita identificar a rede de proteção socioassistencial e avaliar a quantidade e qualidade de oferta dos serviços. Ainda neste campo, o aprimoramento do Cadastro Nacional do SUAS – CadSUAS e a implantação do Registro Mensal de Atendimentos dos CRAS e CREAS constituem ações de grande relevância.

O aprimoramento do Cadastro Único de Programas Sociais – CadÚnico e o desenvolvimento de ferramentas para que os municípios possam extrair e analisar os dados é, finalmente, uma realidade. Hoje, técnicos e gestores do SUAS podem acessar com facilidade os dados do CadÚnico por meio do sistema CECAD – Consulta, Seleção e Extração de Informações do CadÚnico. O acesso a essas informações viabiliza a construção de diagnósticos territoriais mais detalhados, assim como de análises das situações de vulnerabilidade da população e da demanda potencial por serviços socioassistenciais, bem como o planejamento de ações de busca ativa das famílias e indivíduos mais vulneráveis (e já cadastrados) visando a inclusão dos mesmos em nossos serviços, especialmente no PAIF e em serviços de convivência e fortalecimento de vínculos.

Vale lembrar que a indução e criação de meios para potencialização de ações de busca ativa teve origem já em 2008 com o *Protocolo de Gestão Integrada de Serviço, Benefícios e Transferências de Renda*, aprovado pelo CNAS, e que aponta estratégias de priorização para o atendimento de famílias beneficiárias do Bolsa Família e do Benefício de Prestação Continuada – BPC, além de famílias com presença de trabalho infantil.

Também no campo da elaboração de estudos e diagnósticos, merece destaque a criação do *Sistema de Identificação de Domicílios em Vulnerabilidade - IDV*, aplicativo on-line, disponível para usuário em geral, desenvolvido para construção de mapas de pobreza ao nível de estados, municípios e setores censitários, apresentando dados e indicadores de pobreza, vulnerabilidade e grupos populacionais específicos, baseado em informações do Instituto Brasileiro de Geografia e Estatísticas – IBGE.

Outra iniciativa de grande importância foi a elaboração de um padrão nacional para os Prontuários do SUAS. Neste quesito, em abril de 2013, iniciou-se a distribuição do modelo de Prontuário SUAS proposto pelo MDS. O Prontuário apresenta uma proposta nacional sobre quais as informações mínimas que devem ser registradas pelas equipes de referência dos CRAS e dos CREAS para a qualificação do processo de acompanhamento familiar. O Prontuário SUAS tem como objetivo oferecer aos profissionais dos CRAS e dos CREAS um instrumento que auxilie e oriente a organização das informações relativas ao processo de acompanhamento das famílias e indivíduos. Espera-se que seja capaz de induzir o aprimoramento do processo de trabalho, dando visibilidade às múltiplas dimensões que devem ser consideradas no processo de acompanhamento familiar. Ao constituir-se como um documento sob guarda da Unidade no qual passam a estar registradas e arquivadas, de maneira organizada, todas as informações referentes às intervenções realizadas com a família, o Prontuário traz ganhos, não apenas para as equipes multi profi ssionais que trabalham nas Unidades, mas também para as próprias famílias, que ao passarem a ter preservado o seu histórico de atendimentos estarão menos expostas ao “eterno recontar” de suas vidas, repedidas vezes e para diferentes profissionais.

Quanto a meta de capacitar os trabalhadores do SUAS para a identificação de vulnerabilidades, riscos e eventos decorrentes de situação de pobreza e de violência, de forma a exercerem no cotidiano a Vigilância Socioassistencial, deve-se destacar a criação do Programa CapacitaSUAS, com transferência de recursos federais para que sejam realizadas as ações previstas nos Planos Estaduais de Capacitação.

Por certo, ainda há muito caminho a ser percorrido para a plena implantação da Vigilância Socioassistencial em todos os municípios, estados e na União. A Vigilância deve se materializar concretamente no cotidiano dos territórios, permeando a visão e as ações dos trabalhadores e gestores do SUAS. Contudo, para que alcancemos este objetivo é fundamental a organização das áreas de vigilância dentro dos órgãos gestores da Assistência Social. A organização dessas áreas visa dar a necessária retaguarda de gestão para subsidiar e colaborar com a ação dos trabalhadores da rede socioassistencial. A organização dessas áreas deve se dar de acordo com as diferentes realidades municipais. Num contexto nacional em que 70% dos municípios são de Pequeno Porte I, certamente o caminho para muitos municípios será a definição de um Técnico de Referência que possa estar dedicado exclusivamente a Vigilância Socioassistencial na estrutura da Secretaria. Já nos grandes municípios e metrópoles, tanto a necessidade quanto a possibilidade apontam para a criação de equipes multiprofissionais. Parte do caminho ainda precisa ser construído, mas certamente os trabalhadores e gestores do SUAS não pouparão esforços para continuar avançando.