# Introdução  {.unnumbered}

## Introdução e Objetivo

Este documento tem como objetivo apoiar técnicos e gestores estaduais e municipais envolvidos no desafio de implantação da Vigilância Socioassistencial. Nele o leitor encontrará uma sistematização da base conceitual e normativa da Vigilância, assim como informações e orientações práticas para a implantação ou organização desta área técnica em suas respectivas Secretarias.

No atual estágio de desenvolvimento do SUAS tornam-se cada vez mais visíveis os desafios referentes ao fortalecimento da gestão e qualificação dos serviços; desafios estes cujo enfrentamento pressupõe a organização efetiva da Vigilância Socioassistencial. O desenvolvimento de capacidades de planejamento e gestão torna-se crucial para o amadurecimento da assistência social como política pública setorial, a qual compete garantir ou mediar o acesso a direitos sociais específicos. Nesse contexto, os processos de produção, análise e utilização de informações ganham relevância na medida em que possibilitam qualificar a intervenção dos agentes públicos de forma que suas ações produzam processos e resultados mais condizentes com as expectativas e necessidades da população em geral e, em particular, dos segmentos sociais mais vulneráveis.

É fato que, de algum modo e em alguma medida, parte das atividades de Vigilância abordadas neste documento já são realizadas por todos os estados e municípios. Entretanto, ao serem realizadas de maneira dispersa, incompleta e assistemática raramente alcançam os resultados necessários para impactar melhorias na gestão e nos serviços. A Vigilância deve ser capaz de ampliar a capacidade de Proteção e Defesa de Direitos inerentes à concepção do SUAS, daí advém sua força como função da Política de Assistência Social e seu reconhecimento e valorização na LOAS, na PNAS e na NOB.

Em decorrência dos esforços coletivos realizados ao longo dos últimos oito anos, podemos afirmar que hoje estão postas as condições objetivas para a implantação da Vigilância. Nunca antes a área de assistência social dispôs de tantas informações sobre suas estruturas de gestão sobre suas ofertas de serviços e benefícios e sobre o universo e as características da população mais vulnerável do nosso país; resta-nos, portanto, a obrigação de desenvolvermos capacidades para utilização dessas informações em prol da melhoria da gestão e da qualidade dos serviços prestados à população.

A organização da função de Vigilância Socioassistencial é uma tarefa desafiadora que, por certo, exige priorização, esforço e investimento. Contudo, está em nossas mãos a responsabilidade de tornar real este “salto qualitativo” da política de Assistência Social. Certamente, seremos capazes de compreender a importância dessa tarefa para o fortalecimento e consolidação do SUAS e, uma vez mais, dar respostas concretas aos desafios postos no momento presente, para que em futuro breve outros desafios possam ser enfrentados. Esperamos, sinceramente, que este documento seja uma contribuição relevante para este processo.